import { useState } from 'react';
import {
  PageHeader, Card, SectionTitle,
  RoadmapBadge, triggerComingSoon,
} from '@/components/ui';
import {
  FileText, Download, Share2, Mail, Calendar, Send, Sparkles,
  CheckCircle2, Clock, FileBarChart,
} from 'lucide-react';

export function AIReports() {
  const [shared, setShared] = useState(false);
  const [scheduled, setScheduled] = useState(false);

  const reports = [
    { id: 'r1', title: 'Q1 vs Q2 European Fleet Performance Report', type: 'Quarterly comparison', date: 'Today 08:00', status: 'Generated', icon: FileBarChart },
    { id: 'r2', title: 'Sustainability Report — Q2 2026', type: 'Sustainability', date: 'Yesterday 18:00', status: 'Generated', icon: FileBarChart },
    { id: 'r3', title: 'Card Renewal Status Report', type: 'Operational', date: '2 days ago', status: 'Generated', icon: FileText },
    { id: 'r4', title: 'Fraud & Risk Report — Q2 2026', type: 'Risk', date: '3 days ago', status: 'Generated', icon: FileText },
    { id: 'r5', title: 'Monthly Fleet Cost Report — June', type: 'Monthly', date: '01 Jul 2026', status: 'Scheduled', icon: Calendar },
    { id: 'r6', title: 'Charging Network Performance', type: 'Energy', date: '28 Jun 2026', status: 'Generated', icon: FileText },
  ];

  return (
    <div className="pb-ai-bar max-w-7xl mx-auto">
      <PageHeader
        title="AI Reports"
        subtitle="Natural-language fleet reporting with structured output and scheduling"
        badge={<RoadmapBadge phase={3} />}
        actions={
          <button onClick={() => triggerComingSoon('Generate report')} className="btn-primary btn-sm"><Sparkles size={14} /> Generate report</button>
        }
      />

      {/* Latest report preview */}
      <Card className="p-5 mb-6">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-8 h-8 rounded-lg bg-edenred-50 flex items-center justify-center">
            <FileBarChart size={18} className="text-edenred-600" />
          </div>
          <div>
            <p className="text-sm font-semibold text-ink-800">Latest Report</p>
            <p className="text-xs text-ink-500">Generated by Edenred Mobility Intelligence</p>
          </div>
        </div>

        <h2 className="text-lg font-bold text-ink-900 mb-1">Q1 vs Q2 European Fleet Performance Report</h2>
        <p className="text-sm text-ink-500 mb-4">NordFleet Logistics GmbH</p>

        <p className="text-sm text-ink-600 leading-relaxed mb-4">
          Total fleet mobility spend increased from €4.72M in Q1 to €5.08M in Q2, an increase of 7.6%. Growth was primarily
          driven by public EV charging, German diesel costs and additional cross-border travel. Cost per kilometre increased
          3.8%, while EV fleet utilisation improved by 9.2%.
        </p>

        <div className="overflow-x-auto scrollbar-thin mb-4">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-ink-200">
                <th className="text-left text-xs font-semibold text-ink-500 uppercase px-3 py-2">Metric</th>
                <th className="text-right text-xs font-semibold text-ink-500 uppercase px-3 py-2">Q1</th>
                <th className="text-right text-xs font-semibold text-ink-500 uppercase px-3 py-2">Q2</th>
                <th className="text-right text-xs font-semibold text-ink-500 uppercase px-3 py-2">Change</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['Total mobility spend', '€4.72M', '€5.08M', '+7.6%'],
                ['Fuel spend', '€2.68M', '€2.79M', '+4.1%'],
                ['EV charging spend', '€374K', '€428K', '+14.4%'],
                ['Cost per kilometre', '€0.42', '€0.44', '+3.8%'],
                ['Charging sessions', '16,804', '18,462', '+9.9%'],
                ['CO₂ emissions', '3,840 t', '3,610 t', '-6.0%'],
              ].map((row, i) => (
                <tr key={i} className="border-b border-ink-100">
                  <td className="px-3 py-2 text-ink-700">{row[0]}</td>
                  <td className="px-3 py-2 text-right text-ink-600">{row[1]}</td>
                  <td className="px-3 py-2 text-right text-ink-600">{row[2]}</td>
                  <td className={`px-3 py-2 text-right font-medium ${row[3].includes('-') ? 'text-emerald-600' : 'text-edenred-600'}`}>{row[3]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button onClick={() => triggerComingSoon('Download PDF')} className="btn-secondary btn-sm"><Download size={14} /> PDF</button>
          <button onClick={() => triggerComingSoon('Download Excel')} className="btn-secondary btn-sm"><Download size={14} /> Excel</button>
          <button onClick={() => setShared(!shared)} className="btn-secondary btn-sm"><Share2 size={14} /> {shared ? 'Shared' : 'Share'}</button>
          <button onClick={() => triggerComingSoon('Email Fleet Director')} className="btn-secondary btn-sm"><Mail size={14} /> Email Fleet Director</button>
          <button onClick={() => setScheduled(!scheduled)} className="btn-secondary btn-sm"><Calendar size={14} /> {scheduled ? 'Scheduled' : 'Schedule Quarterly'}</button>
          <button onClick={() => triggerComingSoon('Send to Teams')} className="btn-primary btn-sm"><Send size={14} /> Send to Teams</button>
        </div>
      </Card>

      {/* Report history */}
      <SectionTitle title="Report History" />
      <div className="space-y-3">
        {reports.map((r) => {
          const Icon = r.icon;
          return (
            <Card key={r.id} hover className="p-4">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-lg bg-ink-50 flex items-center justify-center flex-shrink-0">
                  <Icon size={18} className="text-ink-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-ink-800">{r.title}</p>
                  <p className="text-xs text-ink-500">{r.type} · {r.date}</p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {r.status === 'Generated' ? (
                    <span className="badge-success"><CheckCircle2 size={12} /> Generated</span>
                  ) : (
                    <span className="badge-info"><Clock size={12} /> Scheduled</span>
                  )}
                  <button onClick={() => triggerComingSoon('Download report')} className="btn-ghost btn-sm"><Download size={14} /></button>
                  <button onClick={() => triggerComingSoon('Share report')} className="btn-ghost btn-sm"><Share2 size={14} /></button>
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      {/* Report sections */}
      <SectionTitle title="Report Sections" />
      <Card className="p-4 mb-6">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          {[
            'Executive summary', 'Fleet cost overview', 'Fuel performance', 'EV charging performance',
            'Country comparison', 'Driver & vehicle performance', 'Card renewal status', 'Fraud and risk',
            'Operational alerts', 'Sustainability', 'Forecast', 'Recommendations',
            'Actions', 'Sources', 'Confidence', 'Audit trail',
          ].map((section, i) => (
            <div key={i} className="flex items-center gap-2 p-2 rounded-lg hover:bg-ink-50 transition-colors cursor-pointer">
              <FileText size={14} className="text-ink-400 flex-shrink-0" />
              <span className="text-sm text-ink-600">{section}</span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
